/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import ClassesTabelas.Cliente;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import DAO.DAOCliente;

/**
 *
 * @author Erick hayakawa & Lucas Serpa
 */
public class FR_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form FR_Cliente
     */
    public FR_Cliente() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    // metodos de validação
    private Boolean ValidacaoVazio(){
        if(JT_nome.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nome vazio", "Novo Cliente", WIDTH);
            return false;
        }else if(JFT_data.getText().isEmpty()){
            System.out.println(JFT_data.getText());
            JOptionPane.showMessageDialog(this, "Data vazio", "Novo Cliente", WIDTH);
            return false;
        }else if(JT_endereco.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Endereço vazio", "Novo Cliente", WIDTH);
            return false;
        }else if(JT_telefone.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Telefone vazio", "Novo Cliente", WIDTH);
            return false;
        }else if(JT_email.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Data de nascimento vazio", "Novo Cliente", WIDTH);
            return false;
        }
        return true;
    }
    
    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_titulo = new javax.swing.JLabel();
        JL_nome = new javax.swing.JLabel();
        JL_data_nasc = new javax.swing.JLabel();
        JL_endereco = new javax.swing.JLabel();
        JL_telefone = new javax.swing.JLabel();
        JL_email = new javax.swing.JLabel();
        JT_nome = new javax.swing.JTextField();
        JT_endereco = new javax.swing.JTextField();
        JT_telefone = new javax.swing.JTextField();
        JT_email = new javax.swing.JTextField();
        BTN_voltar = new javax.swing.JButton();
        BTN_salvar = new javax.swing.JButton();
        JFT_data = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JL_titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_titulo.setText("Cadastro do cliente");

        JL_nome.setText("Nome:");

        JL_data_nasc.setText("Data do nascimento:");

        JL_endereco.setText("Endereço:");

        JL_telefone.setText("Telefone:");

        JL_email.setText("E-mail:");

        BTN_voltar.setText("Voltar");
        BTN_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_voltarActionPerformed(evt);
            }
        });

        BTN_salvar.setText("Salvar");
        BTN_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_salvarActionPerformed(evt);
            }
        });

        try {
            JFT_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(JL_titulo)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_voltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_salvar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JL_nome)
                            .addComponent(JL_email)
                            .addComponent(JL_telefone)
                            .addComponent(JL_endereco)
                            .addComponent(JL_data_nasc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JT_telefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(JT_email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT_nome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT_endereco)
                            .addComponent(JFT_data, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_titulo)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_nome)
                    .addComponent(JT_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_data_nasc)
                    .addComponent(JFT_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_endereco)
                    .addComponent(JT_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_telefone)
                    .addComponent(JT_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_email)
                    .addComponent(JT_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_voltar)
                    .addComponent(BTN_salvar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_salvarActionPerformed
        if(ValidacaoVazio()){
            //Arrumando o String para Conversão em DATA
            String[] separador = JFT_data.getText().split("/");
            String data = separador[2] + "-" + separador[1] + "-" + separador[0];
            
            //populando Local
            Cliente cli = new Cliente();
            cli.salvarLocal(JT_nome.getText(), data, JT_endereco.getText(), JT_telefone.getText(), JT_email.getText());
            
            //populando BD
            DAOCliente daoCliente = new Cliente();
            daoCliente.salvarBD(cli);
            
            FR_Cadastrar cadastro = new FR_Cadastrar();
            cadastro.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_BTN_salvarActionPerformed

    private void BTN_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_voltarActionPerformed
        FR_Cadastrar cadastro = new FR_Cadastrar();
        cadastro.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BTN_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        /*int[] dias = new int[31];
        for(int i = 0; i < 31; i++){
            dias[i] = i + 1;
        }*/
        String[] dias = new String[31];
        for(int i = 0; i < dias.length; i++) {
            dias[i] = Integer.toString(i + 1);
        }
        JComboBox comboBox = new JComboBox(dias);
        
        
        int[] mes = new int[12];
        for(int i = 0; i < 12 ; i++){
            mes[i] = i + 1;
        }
        
        int[] ano = new int[100];
        for(int i = 2020; i > 1980; i--){
            ano[i] = i;
        }
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FR_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FR_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FR_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FR_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FR_Cliente().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_salvar;
    private javax.swing.JButton BTN_voltar;
    private javax.swing.JFormattedTextField JFT_data;
    private javax.swing.JLabel JL_data_nasc;
    private javax.swing.JLabel JL_email;
    private javax.swing.JLabel JL_endereco;
    private javax.swing.JLabel JL_nome;
    private javax.swing.JLabel JL_telefone;
    private javax.swing.JLabel JL_titulo;
    private javax.swing.JTextField JT_email;
    private javax.swing.JTextField JT_endereco;
    private javax.swing.JTextField JT_nome;
    private javax.swing.JTextField JT_telefone;
    // End of variables declaration//GEN-END:variables
}
