/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Erick hayakawa & Lucas Serpa
 */
public class FR_Cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar
     */
    public FR_Cadastrar() {
        initComponents();
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_titulo = new javax.swing.JLabel();
        BTN_Cliente = new javax.swing.JButton();
        BNT_Vendas = new javax.swing.JButton();
        BTN_Itens = new javax.swing.JButton();
        BTN_Produtos = new javax.swing.JButton();
        BTN_Distribuidores = new javax.swing.JButton();
        JB_voltar = new javax.swing.JButton();
        JB_consultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JL_titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_titulo.setText("Selecione o que deseja cadastrar");

        BTN_Cliente.setText("Cliente");
        BTN_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ClienteActionPerformed(evt);
            }
        });

        BNT_Vendas.setText("Vendas");
        BNT_Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNT_VendasActionPerformed(evt);
            }
        });

        BTN_Itens.setText("Itens");
        BTN_Itens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ItensActionPerformed(evt);
            }
        });

        BTN_Produtos.setText("Produtos");
        BTN_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ProdutosActionPerformed(evt);
            }
        });

        BTN_Distribuidores.setText("Distribuidores");
        BTN_Distribuidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DistribuidoresActionPerformed(evt);
            }
        });

        JB_voltar.setText("Voltar");
        JB_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_voltarActionPerformed(evt);
            }
        });

        JB_consultar.setText("Consultar");
        JB_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_consultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(JL_titulo)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BTN_Cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BNT_Vendas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_Itens))
                    .addComponent(JB_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_consultar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_Produtos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_Distribuidores)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Cliente)
                    .addComponent(BNT_Vendas)
                    .addComponent(BTN_Itens)
                    .addComponent(BTN_Produtos)
                    .addComponent(BTN_Distribuidores))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_consultar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ClienteActionPerformed
        setVisible(false);
        FR_Cliente frame = new FR_Cliente();
        frame.setVisible(true);
    }//GEN-LAST:event_BTN_ClienteActionPerformed

    private void BNT_VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNT_VendasActionPerformed
        setVisible(false);
        FR_Venda frame = new FR_Venda();
        frame.setVisible(true);
    }//GEN-LAST:event_BNT_VendasActionPerformed

    private void BTN_ItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ItensActionPerformed
        setVisible(false);
        FR_Itens frame = new FR_Itens();
        frame.setVisible(true);
    }//GEN-LAST:event_BTN_ItensActionPerformed

    private void BTN_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ProdutosActionPerformed
        setVisible(false);
        FR_Produtos frame = new FR_Produtos();
        frame.setVisible(true);
    }//GEN-LAST:event_BTN_ProdutosActionPerformed

    private void BTN_DistribuidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DistribuidoresActionPerformed
        setVisible(false);
        FR_Distribuidores frame = new FR_Distribuidores();
        frame.setVisible(true);
    }//GEN-LAST:event_BTN_DistribuidoresActionPerformed

    private void JB_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_voltarActionPerformed
        FR_Inicio inicio = new FR_Inicio();
        inicio.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_JB_voltarActionPerformed

    private void JB_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_consultarActionPerformed
        setVisible(false);
        FR_Escolha_consulta frame = new FR_Escolha_consulta();
        frame.setVisible(true);
    }//GEN-LAST:event_JB_consultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FR_Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FR_Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FR_Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FR_Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FR_Cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BNT_Vendas;
    private javax.swing.JButton BTN_Cliente;
    private javax.swing.JButton BTN_Distribuidores;
    private javax.swing.JButton BTN_Itens;
    private javax.swing.JButton BTN_Produtos;
    private javax.swing.JButton JB_consultar;
    private javax.swing.JButton JB_voltar;
    private javax.swing.JLabel JL_titulo;
    // End of variables declaration//GEN-END:variables
}
