/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import ClassesTabelas.Distribuidores;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;
import DAO.DAOCliente;
import DAO.DAODistribuidores;

/**
 *
 * @author Erick hayakawa & Lucas Serpa
 */
public class FR_Distribuidores extends javax.swing.JFrame {

    /**
     * Creates new form JF_Distribuidores
     */
    public FR_Distribuidores() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private Boolean ValidacaoVazio(){
        if(JT_nome.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nome vazio", "Novo Cliente", WIDTH);
            return false;
        }else if(JT_razao_social.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Razão social vazio", "Novo Cliente", WIDTH);
            return false;
        }else if(JT_telefone.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Telefone vazio", "Novo Cliente", WIDTH);
            return false;
        }else if(JT_email.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Data de nascimento vazio", "Novo Cliente", WIDTH);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JT_nome = new javax.swing.JTextField();
        JT_razao_social = new javax.swing.JTextField();
        JT_email = new javax.swing.JTextField();
        JT_telefone = new javax.swing.JTextField();
        JL_titulo = new javax.swing.JLabel();
        JL_nome = new javax.swing.JLabel();
        JL_razao_social = new javax.swing.JLabel();
        JL_email = new javax.swing.JLabel();
        JL_telefone = new javax.swing.JLabel();
        BTN_voltar = new javax.swing.JButton();
        BTN_salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JL_titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_titulo.setText("Cadastro do distribuidor");

        JL_nome.setText("Nome:");

        JL_razao_social.setText("Razão social:");

        JL_email.setText("E-mail:");

        JL_telefone.setText("Telefone:");

        BTN_voltar.setText("Voltar");
        BTN_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_voltarActionPerformed(evt);
            }
        });

        BTN_salvar.setText("Salvar");
        BTN_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JL_titulo)
                .addGap(122, 122, 122))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_voltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_salvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JL_nome)
                            .addComponent(JL_telefone)
                            .addComponent(JL_email)
                            .addComponent(JL_razao_social))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_razao_social, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_email, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_titulo)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_nome)
                    .addComponent(JT_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_razao_social)
                    .addComponent(JT_razao_social, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_email)
                    .addComponent(JT_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_telefone)
                    .addComponent(JT_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_voltar)
                    .addComponent(BTN_salvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_salvarActionPerformed
        if(ValidacaoVazio()){            
            //populando Local
            Distribuidores dis = new Distribuidores();
            dis.salvarLocal(JT_nome.getText(), JT_razao_social.getText(), JT_telefone.getText(), JT_email.getText());
            
            //populando BD
            DAODistribuidores daoDistribuidores = new Distribuidores();
            daoDistribuidores.SalvarBD(dis);
            
            FR_Cadastrar cadastro = new FR_Cadastrar();
            cadastro.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_BTN_salvarActionPerformed

    private void BTN_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_voltarActionPerformed
        FR_Cadastrar cadastro = new FR_Cadastrar();
        cadastro.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BTN_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FR_Distribuidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FR_Distribuidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FR_Distribuidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FR_Distribuidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FR_Distribuidores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_salvar;
    private javax.swing.JButton BTN_voltar;
    private javax.swing.JLabel JL_email;
    private javax.swing.JLabel JL_nome;
    private javax.swing.JLabel JL_razao_social;
    private javax.swing.JLabel JL_telefone;
    private javax.swing.JLabel JL_titulo;
    private javax.swing.JTextField JT_email;
    private javax.swing.JTextField JT_nome;
    private javax.swing.JTextField JT_razao_social;
    private javax.swing.JTextField JT_telefone;
    // End of variables declaration//GEN-END:variables
}
