/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import ConexaoBD.ConexaoBD;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erick hayakawa & Lucas Serpa
 */
public class FR_Escolha_consulta extends javax.swing.JFrame {

    /**
     * Creates new form FR_Consulta
     */
    public FR_Escolha_consulta() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_titulo = new javax.swing.JLabel();
        JB_cliente_email = new javax.swing.JButton();
        JB_produtos_vencidos = new javax.swing.JButton();
        JB_vendas_2020 = new javax.swing.JButton();
        JB_Vendas = new javax.swing.JButton();
        JB_cadastrar = new javax.swing.JButton();
        JB_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JL_titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_titulo.setText("Escolha a consulta desejada");

        JB_cliente_email.setText("Cliente sem e-mail");
        JB_cliente_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_cliente_emailActionPerformed(evt);
            }
        });

        JB_produtos_vencidos.setText("Produtos vencidos");
        JB_produtos_vencidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_produtos_vencidosActionPerformed(evt);
            }
        });

        JB_vendas_2020.setText("Vendas em 2020");
        JB_vendas_2020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_vendas_2020ActionPerformed(evt);
            }
        });

        JB_Vendas.setText("Listar vendas");
        JB_Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_VendasActionPerformed(evt);
            }
        });

        JB_cadastrar.setText("Cadastrar");
        JB_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_cadastrarActionPerformed(evt);
            }
        });

        JB_voltar.setText("Voltar");
        JB_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JL_titulo)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JB_cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_voltar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JB_cliente_email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB_produtos_vencidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB_vendas_2020)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB_Vendas)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_titulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_cliente_email)
                    .addComponent(JB_produtos_vencidos)
                    .addComponent(JB_vendas_2020)
                    .addComponent(JB_Vendas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_cadastrar)
                    .addComponent(JB_voltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void JB_cliente_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_cliente_emailActionPerformed
        try {
            ConexaoBD conect = new ConexaoBD();
            Connection connection = conect.Conexao_banco();

            Statement sta = connection.createStatement();
            String str = "select * from Clientes where Email is null";
            ResultSet result = sta.executeQuery(str);
            while(result.next()){
                JOptionPane.showMessageDialog(null,"Nome: " +result.getString("Nome")+" \nData de Nascimento: "+ result.getString("Data_nasc")+" \nEndereço: "+ result.getString("Endereco")+" \nTelefone: "+ result.getString("Telefone"), "Consulta", JOptionPane.INFORMATION_MESSAGE);
            }     
            connection.close();
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_JB_cliente_emailActionPerformed

    private void JB_produtos_vencidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_produtos_vencidosActionPerformed
        try {
            ConexaoBD conect = new ConexaoBD();
            Connection connection = conect.Conexao_banco();

            Statement sta = connection.createStatement();
            String str = "SELECT * FROM Produtos where Data_validade < getDate()";
            ResultSet result = sta.executeQuery(str);
            while(result.next()){
                JOptionPane.showMessageDialog(null,"Preco Venda: "+ result.getString("Preco_venda") + " \nDescrição: " +result.getString("Descricao") + " \nData_Validade: " + result.getString("Data_validade") + " \nPreço de custo: " + result.getString("Preco_custo") + " \nEstoque: " + result.getString("estoque"), "Consulta", JOptionPane.INFORMATION_MESSAGE);
            }     
            connection.close();
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_JB_produtos_vencidosActionPerformed

    private void JB_vendas_2020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_vendas_2020ActionPerformed
        try {
            ConexaoBD conect = new ConexaoBD();
            Connection connection = conect.Conexao_banco();

            Statement sta = connection.createStatement();
            String str = "select CL.Nome as cliente, count(*) as quant from Vendas ven JOIN Clientes CL ON CL.ID_cli = ven.ID_cli where Data_vend like '%2020%' group by CL.Nome";
            ResultSet result = sta.executeQuery(str);
             
            while(result.next()){
             
                JOptionPane.showMessageDialog(null,"Nome: " +result.getString(1)+"\n Quantidade de vendas: "+ result.getString(2), "Consulta", JOptionPane.INFORMATION_MESSAGE);
                    
            }  
            connection.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_JB_vendas_2020ActionPerformed

    private void JB_VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_VendasActionPerformed
        try {
            ConexaoBD conect = new ConexaoBD();
            Connection connection = conect.Conexao_banco();

            Statement sta = connection.createStatement();
            String str = "select * from Vendas";
            ResultSet result = sta.executeQuery(str);
            Statement sta2 = connection.createStatement();
            String str2 = "SELECT SUM(Vendas.Total) as soma_total_vendas FROM Vendas";
            ResultSet result2 = sta2.executeQuery(str2);
            result2.next();
              
                
            while(result.next()){
                JOptionPane.showMessageDialog(null,"Data da venda:"+result.getString("Data_vend")+" \nHora:" + result.getString("Hora") + "\nTotal: "+result.getString("Total"), "Consulta", JOptionPane.INFORMATION_MESSAGE);
            }
            JOptionPane.showMessageDialog(null,"Volor total das vendas: "+result2.getString(1), "Consulta", JOptionPane.INFORMATION_MESSAGE);
            connection.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Erro", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_JB_VendasActionPerformed

    private void JB_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_cadastrarActionPerformed
        FR_Cadastrar cadastro = new FR_Cadastrar();
        cadastro.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_JB_cadastrarActionPerformed

    private void JB_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_voltarActionPerformed
        FR_Inicio inicio = new FR_Inicio();
        inicio.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_JB_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FR_Escolha_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FR_Escolha_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FR_Escolha_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FR_Escolha_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FR_Escolha_consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Vendas;
    private javax.swing.JButton JB_cadastrar;
    private javax.swing.JButton JB_cliente_email;
    private javax.swing.JButton JB_produtos_vencidos;
    private javax.swing.JButton JB_vendas_2020;
    private javax.swing.JButton JB_voltar;
    private javax.swing.JLabel JL_titulo;
    // End of variables declaration//GEN-END:variables
}
