/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import ClassesTabelas.Produtos;
import ClassesTabelas.Vendas;
import ConexaoBD.ConexaoBD;
import DAO.DAOProdutos;
import DAO.DAOVendas;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick hayakawa & Lucas Serpa
 */
public class FR_Produtos extends javax.swing.JFrame {

    /**
     * Creates new form FR_Produtos
     */
    public FR_Produtos() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private Boolean ValidacaoVazio(){
        if(JT_preco_venda.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Preço de venda vazio", "Novo Cliente", WIDTH);
            return false;
        }else if(JFT_data.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Data de nascimento vazio", "Novo Cliente", WIDTH);
            return false;
        }else if(JT_preco_custo.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Preco de custo vazio", "Novo Cliente", WIDTH);
            return false;
        }else if(JT_estoque.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nome do cliente vazio", "Novo Cliente", WIDTH);
            return false;
        }else if(JT_descricao.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nome do cliente vazio", "Novo Cliente", WIDTH);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JT_preco_venda = new javax.swing.JTextField();
        JT_descricao = new javax.swing.JTextField();
        JT_preco_custo = new javax.swing.JTextField();
        JT_estoque = new javax.swing.JTextField();
        JL_titulo = new javax.swing.JLabel();
        JL_preco_venda = new javax.swing.JLabel();
        JL_descricao = new javax.swing.JLabel();
        JL_validade = new javax.swing.JLabel();
        JL_preco_custo = new javax.swing.JLabel();
        JL_estoque = new javax.swing.JLabel();
        BTN_voltar = new javax.swing.JButton();
        BTN_salvar = new javax.swing.JButton();
        JL_produto = new javax.swing.JLabel();
        JL_produto1 = new javax.swing.JLabel();
        JFT_data = new javax.swing.JFormattedTextField();
        JC_id_dist = new javax.swing.JComboBox<>();
        JC_id_item = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        JL_titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_titulo.setText("Cadastro de Produtos");

        JL_preco_venda.setText("Preço na venda:");

        JL_descricao.setText("Descrição:");

        JL_validade.setText("Data de Validade:");

        JL_preco_custo.setText("Preço do custo:");

        JL_estoque.setText("Estoque:");

        BTN_voltar.setText("Voltar");
        BTN_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_voltarActionPerformed(evt);
            }
        });

        BTN_salvar.setText("Salvar");
        BTN_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_salvarActionPerformed(evt);
            }
        });

        JL_produto.setText("Nome do Distribuidor:");

        JL_produto1.setText("Sub total do item:");

        try {
            JFT_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(JL_titulo)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_voltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_salvar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JL_preco_venda)
                            .addComponent(JL_estoque)
                            .addComponent(JL_preco_custo)
                            .addComponent(JL_validade)
                            .addComponent(JL_descricao)
                            .addComponent(JL_produto)
                            .addComponent(JL_produto1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JT_preco_venda, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(JT_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(JT_preco_custo, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(JT_estoque, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(JFT_data)
                            .addComponent(JC_id_dist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JC_id_item, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_titulo)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_preco_venda)
                    .addComponent(JT_preco_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_descricao)
                    .addComponent(JT_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_validade)
                    .addComponent(JFT_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_preco_custo)
                    .addComponent(JT_preco_custo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_estoque)
                    .addComponent(JT_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_produto)
                    .addComponent(JC_id_dist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_produto1)
                    .addComponent(JC_id_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_voltar)
                    .addComponent(BTN_salvar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_salvarActionPerformed
        if(ValidacaoVazio()){
            String[] dia_mes = JFT_data.getText().split("/");
            String data = dia_mes[2] + "-" + dia_mes[1] +"-"+ dia_mes[0];
            
            Produtos prod = new Produtos();
            String[] ID_dis = JC_id_dist.getSelectedItem().toString().split(" ");
            String[] ID_item = JC_id_item.getSelectedItem().toString().split(" ");
            prod.salvarLocal(Double.parseDouble(JT_preco_venda.getText()), JT_descricao.getText(), data, Double.parseDouble(JT_preco_custo.getText()), Integer.parseInt(JT_estoque.getText()), Integer.parseInt(ID_item[0]), Integer.parseInt(ID_dis[0]));

            
            DAOProdutos produtos = new Produtos();
            produtos.SalvarBD(prod);
            
            FR_Cadastrar cadastro = new FR_Cadastrar();
            cadastro.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_BTN_salvarActionPerformed

    private void BTN_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_voltarActionPerformed
        FR_Cadastrar cadastro = new FR_Cadastrar();
        cadastro.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BTN_voltarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        JC_id_dist.removeAllItems();
        JC_id_item.removeAllItems();
        try {
            ConexaoBD conect = new ConexaoBD();
            Connection connection = conect.Conexao_banco();
            
            Statement sta = connection.createStatement();
            String str = "Select * from Distribuidores";
            ResultSet result = sta.executeQuery(str);
            while(result.next()){
                JC_id_dist.addItem(result.getInt(1)+" - "+result.getString(2));
            }
            
            str = "Select * from Itens_Venda";
            result = sta.executeQuery(str);
            while(result.next()){
                JC_id_item.addItem(result.getInt(1)+" - "+result.getString(3));
            }
            connection.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Popularização do JCombo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FR_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FR_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FR_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FR_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FR_Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_salvar;
    private javax.swing.JButton BTN_voltar;
    private javax.swing.JComboBox<String> JC_id_dist;
    private javax.swing.JComboBox<String> JC_id_item;
    private javax.swing.JFormattedTextField JFT_data;
    private javax.swing.JLabel JL_descricao;
    private javax.swing.JLabel JL_estoque;
    private javax.swing.JLabel JL_preco_custo;
    private javax.swing.JLabel JL_preco_venda;
    private javax.swing.JLabel JL_produto;
    private javax.swing.JLabel JL_produto1;
    private javax.swing.JLabel JL_titulo;
    private javax.swing.JLabel JL_validade;
    private javax.swing.JTextField JT_descricao;
    private javax.swing.JTextField JT_estoque;
    private javax.swing.JTextField JT_preco_custo;
    private javax.swing.JTextField JT_preco_venda;
    // End of variables declaration//GEN-END:variables
}
